#!/bin/bash 
[ -z "$CFILE" ] && echo "Please provide the C file name in the variable CFILE" && exit 1 OFILE="${CFILE%.c}.s" gcc -S -masm=intel "$CFILE" -o "$OFILE" || echo "There was an error generating the assembly code" && exit 2 -f "$OFILE" ] && echo "The assembly code is saved in $OFILE"
